In [1]:
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [3]:
x,y=load_diabetes(return_X_y=True)

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [11]:
x_train.shape

(353, 10)

In [12]:
x_test.shape

(89, 10)

In [114]:
class Stochastic_Regressor:
    
    def __init__(self,lr,epochs):
        self.coef=None
        self.intercept=None
        self.lr=lr
        self.epochs=epochs
        

    def fit(self,x_train,y_train):
        # starting value of b0=0
        self.intercept=0
        self.coef=np.ones(x_train.shape[1])

        for i in range(self.epochs):
             for j in range(x_train.shape[0]):
                 # we select a random index from 0 to 353
                 # loop utni baar chalega jitne rows honge
                 idx=np.random.randint(0,x_train.shape[0])
                 y_hat=np.dot(x_train[idx],self.coef)+ self.intercept
                 # as only one row, no need of summation and n
                 intercept_der=-2* (y_train[idx]-y_hat)
                 self.intercept=self.intercept-(self.lr*intercept_der)
                 coef_der=-2* (np.dot((y_train[idx]-y_hat),x_train[idx]))
                 self.coef=self.coef-(self.lr*coef_der)
                 
        print(self.coef,self.intercept)
        print(self.coef.shape)
        print(self.intercept.shape)
        # coef should be a vector but intercept should be a scaler(as only beta not)

            
    def predict(self,x_test):
        return(np.dot(x_test,self.coef)+self.intercept)
        

In [75]:
x_train[23]
# matrix of 1*10

array([ 0.01991321,  0.05068012,  0.10480869,  0.0700723 , -0.03596778,
       -0.0266789 , -0.02499266, -0.00259226,  0.00370906,  0.04034337])

In [76]:
np.zeros(x_train.shape[1]).shape

(10,)

In [77]:
np.dot(x_train[23],np.zeros(x_train.shape[1]))

np.float64(0.0)

In [112]:
sgd=Stochastic_Regressor(0.01,50)
sgd.fit(x_train,y_train)
y_pred=sgd.predict(x_test)


[  51.11128696  -66.29532381  361.15823897  257.64270643   10.74367685
  -36.85999322 -172.27221793  118.65704994  319.0470655   134.50230973] 156.09132477247368
(10,)
()


In [113]:
r2_score(y_test,y_pred)

0.4332456369546146

In [79]:
y_train[10]


np.float64(138.0)

In [61]:
x_train[10]

array([ 0.04534098,  0.05068012,  0.00564998,  0.0563009 ,  0.06447678,
        0.08918603, -0.03971921,  0.07120998,  0.01556846, -0.00936191])

In [116]:
from sklearn.linear_model import SGDRegressor

In [117]:
sgd=SGDRegressor(max_iter=100,learning_rate='constant',eta0=0.01)

In [118]:
sgd.fit(x_train,y_train)
sgd.predict(x_test)

C:\Users\Dell\Downloads\anaconda\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:1579: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


array([154.22219221, 191.19485926, 140.52293607, 109.75101898,
       243.93857037, 236.25808862, 108.16103086, 115.51151436,
        93.91059284, 185.24170191, 160.81178248, 172.93930493,
       184.55058461, 151.50914766, 253.11152146,  93.37806179,
       185.74970967, 139.77285759, 140.59313737, 139.8602112 ,
       133.19610766, 190.25248808, 167.04935379, 178.22271127,
       127.27638835, 219.75682251, 194.93231875, 121.80448602,
        64.76698368, 240.61087309, 235.99211118, 120.19439458,
        76.22013877, 111.35934654, 199.64385182, 166.75435745,
       167.46715493, 196.21968858, 116.20514993, 232.49772334,
       136.5578842 , 127.90576382, 185.46471233, 186.32919011,
       170.84148384, 146.78951669, 173.83692438, 277.00037242,
       118.70150216, 189.41321993, 235.60270513, 130.9973463 ,
       144.20177973, 151.1225827 , 189.61125011, 114.86080094,
       156.44372504,  87.44657933, 158.8950669 , 144.16526115,
       164.20861571, 171.78034794, 111.92993003, 204.85

In [119]:
r2_score(y_test,y_pred)

0.4332456369546146